"""
Constants, lookup tables, and reference data for the HVAC Network Scanner.

Split out from the monolithic scanner so unit tests can import these without
pulling in tkinter or the socket layer.

Sources:
- ASHRAE Standard 135 (BACnet) engineering unit enumerations
- BACnet vendor ID registry (https://bacnet.org/assigned-vendor-ids/)
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# BACnet framing
# ---------------------------------------------------------------------------
BACNET_PORT = 47808
BACNET_BVLC_TYPE = 0x81

# ---------------------------------------------------------------------------
# BACnet object types (ASHRAE 135 Table 21-1 partial)
# ---------------------------------------------------------------------------
BACNET_OBJ_TYPES = {
    0: "Analog Input", 1: "Analog Output", 2: "Analog Value",
    3: "Binary Input", 4: "Binary Output", 5: "Binary Value",
    6: "Calendar", 7: "Command", 8: "Device",
    9: "Event Enrollment", 10: "File", 11: "Group",
    12: "Loop", 13: "Multi-State Input", 14: "Multi-State Output",
    15: "Notification Class", 16: "Program", 17: "Schedule",
    18: "Averaging", 19: "Multi-State Value", 20: "Trend Log",
    21: "Life Safety Point", 22: "Life Safety Zone",
    23: "Accumulator", 24: "Pulse Converter",
    25: "Event Log", 26: "Global Group", 27: "Trend Log Multiple",
    28: "Load Control", 29: "Structured View",
    30: "Access Door", 31: "Timer", 54: "Lighting Output",
    57: "Network Port", 58: "Elevator Group", 59: "Escalator",
}

# ---------------------------------------------------------------------------
# BACnet engineering units (ASHRAE 135 Table C.1 / engineering-units enum)
# Corrected from the original scanner:
#   - 118 is gal/s per the standard, NOT L/min (which is 81)
#   - Added commonly-encountered units missing from v1
# ---------------------------------------------------------------------------
BACNET_UNITS = {
    0: "sqm", 1: "sqft", 2: "mA", 3: "A", 4: "ohm",
    5: "V", 6: "kV", 7: "MV", 8: "VA", 9: "kVA",
    10: "MVA", 11: "VAR", 12: "kVAR", 13: "MVAR",
    14: "degrees-phase", 15: "PF",
    17: "psi", 18: "bar", 19: "kPa", 20: "cmH2O", 21: "inH2O",
    22: "mmHg", 23: "centibar",
    24: "BTU/lb", 25: "cal/g", 26: "kcal/kg", 27: "J/kg", 28: "kJ/kg",
    29: "W", 30: "kW", 31: "MW", 32: "BTU/h",
    33: "hp", 34: "ton", 35: "J/h", 36: "kJ/h",
    40: "lux", 41: "fc",
    62: "C", 63: "K", 64: "F",
    65: "C-day", 66: "F-day",
    67: "J", 68: "kJ", 69: "Wh", 70: "kWh",
    71: "BTU", 72: "therm",
    75: "L", 76: "gal", 77: "ft3", 78: "m3",
    80: "L/s", 81: "L/min", 82: "L/h", 83: "gal/min", 84: "CFM",
    85: "m3/h", 86: "m3/s",
    90: "m/s", 91: "km/h", 92: "mph",
    93: "ft/s", 94: "ft/min",
    95: "Pa",                     # duplicates 19 conceptually but standard lists both
    96: "kPa-alt", 97: "mmHg",    # kept for backwards compat
    98: "%", 99: "%/s", 100: "%RH",
    105: "mm", 106: "cm", 107: "m", 108: "in", 109: "ft",
    110: "hr", 111: "RPM", 112: "Hz",
    116: "ppm", 117: "ppb",
    118: "gal/s",                 # CORRECTED from L/min
    119: "gal/min",
    120: "s", 121: "min", 122: "h",
    145: "inWC",
}

# ---------------------------------------------------------------------------
# HVAC service ports (sorted by port # for readable tables)
# ---------------------------------------------------------------------------
HVAC_SERVICES = [
    (21,    "FTP",                "tcp"),
    (22,    "SSH",                "tcp"),
    (23,    "Telnet",             "tcp"),
    (80,    "HTTP",               "tcp"),
    (102,   "Siemens S7 / ISO-TSAP", "tcp"),
    (161,   "SNMP",               "udp"),
    (443,   "HTTPS",              "tcp"),
    (502,   "Modbus TCP",         "tcp"),
    (1628,  "LonWorks/IP",        "tcp"),
    (1883,  "MQTT",               "tcp"),
    (1911,  "Niagara Fox",        "tcp"),
    (2222,  "EtherNet/IP Config", "tcp"),
    (3671,  "KNXnet/IP",          "udp"),
    (4840,  "OPC UA",             "tcp"),
    (4843,  "OPC UA TLS",         "tcp"),
    (4911,  "Niagara Fox TLS",    "tcp"),
    (8000,  "HTTP-8000",          "tcp"),
    (8080,  "HTTP-Alt",           "tcp"),
    (8443,  "HTTPS-Alt",          "tcp"),
    (8883,  "MQTT TLS",           "tcp"),
    (8888,  "HTTP-8888",          "tcp"),
    (9090,  "WebCTRL",            "tcp"),
    (9100,  "Building Ctrl",      "tcp"),
    (10001, "Metasys/JCI",        "tcp"),
    (11001, "Metasys ADX",        "tcp"),
    (44818, "EtherNet/IP CIP",    "tcp"),
    (47808, "BACnet/IP",          "udp"),
    (47820, "BACnet/SC",          "tcp"),
]

HVAC_TCP_PORTS = sorted({p for p, _, t in HVAC_SERVICES if t == "tcp"})
HVAC_UDP_PORTS = sorted({p for p, _, t in HVAC_SERVICES if t == "udp"})
PORT_TO_SERVICE = {(p, t): n for p, n, t in HVAC_SERVICES}

# ---------------------------------------------------------------------------
# BACnet vendor database (partial, extended)
# Full registry: https://bacnet.org/assigned-vendor-ids/
# ---------------------------------------------------------------------------
BACNET_VENDORS = {
    0: "ASHRAE",
    1: "NIST",
    2: "The Trane Company",
    3: "Daikin Applied Americas",
    4: "PolarSoft",
    5: "Johnson Controls",
    6: "ABB (Formerly American Auto-Matrix)",
    7: "Siemens Schweiz",
    8: "Delta Controls",
    9: "Siemens Schweiz",
    10: "Schneider Electric",
    11: "TAC",
    12: "Orion Analysis",
    13: "Teletrol Systems",
    14: "Cimetrics Technology",
    15: "Cornell University",
    16: "United Technologies Carrier",
    17: "Honeywell",
    18: "Alerton / Honeywell",
    19: "TAC",
    20: "Hewlett-Packard Company",
    21: "Dorsette's",
    22: "Siemens Schweiz",
    23: "York Controls Group",
    24: "Automated Logic",
    25: "CSI Control Systems International",
    26: "Phoenix Controls",
    27: "Innovex Technologies",
    28: "KMC Controls",
    29: "Xn Technologies",
    30: "Hyundai Information Technology",
    31: "Tokimec",
    32: "Simplex",
    33: "North Building Technologies Limited",
    34: "Notifier",
    35: "Reliable Controls",
    36: "Tridium",
    37: "MSA Safety",
    38: "Silicon Energy",
    39: "Kieback & Peter GmbH & Co KG",
    40: "Anacon Systems",
    41: "Systems Controls & Instruments",
    42: "Acuity Brands Lighting",
    43: "Micropower Manufacturing",
    44: "Matrix Controls",
    45: "METALAIRE",
    46: "ESS Engineering",
    47: "Sphere Systems Pty",
    48: "Walker Technologies",
    49: "H I Solutions",
    50: "MBS",
    51: "SAMSON",
    52: "Badger Meter",
    53: "DAIKIN Industries",
    54: "NARA Controls",
    55: "Mammoth",
    56: "Liebert",
    57: "SEMCO Incorporated",
    58: "Air Monitor",
    59: "TRIATEK",
    60: "NexLight",
    61: "Multistack",
    62: "TSI Incorporated",
    63: "Weather-Rite",
    64: "Dunham-Bush",
    65: "Reliance Electric",
    66: "LCS",
    67: "Regulator Australia PTY",
    68: "Touch-Plate Lighting Controls",
    69: "Amann",
    70: "Parameter",
    71: "Cardkey Systems",
    72: "SECOM",
    73: "ABB Gebäudetechnik",
    74: "KNX Association",
    75: "IEIEJ (Japan)",
    76: "Nohmi Bosai",
    77: "Carel Industries",
    78: "UTC Fire & Security España",
    79: "Hochiki",
    80: "Fr. Sauter",
    81: "Matsushita Electric Works",
    82: "Mitsubishi Electric (Inazawa Works)",
    83: "Mitsubishi Heavy Industries",
    84: "Xylem",
    85: "Yamatake Building Systems",
    86: "The Watt Stopper",
    87: "Aichi Tokei Denki",
    88: "Activation Technologies",
    89: "Saia-Burgess Controls",
    90: "Hitachi",
    91: "Novar Corp. / Trend Control Systems",
    92: "Mitsubishi Electric Lighting",
    93: "Argus Control Systems",
    94: "Kyuki",
    95: "Richards-Zeta Building Intelligence",
    96: "Scientech R&D",
    97: "VCI Controls",
    98: "Toshiba",
    99: "Mitsubishi Electric Air Conditioning",
    100: "Custom Mechanical Equipment",
    101: "ClimateMaster",
    102: "ICP Panel-Tec",
    103: "D-Tek Controls",
    104: "NEC Engineering",
    105: "PRIVA",
    106: "Meidensha",
    107: "JCI Systems Integration Services",
    108: "Freedom",
    109: "Neuberger Gebäudeautomation",
    110: "eZi Controls",
    111: "Leviton Manufacturing",
    112: "Fujitsu Limited",
    113: "Vertiv (Formerly Emerson Network Power)",
    114: "S. A. Armstrong",
    115: "Visonet",
    116: "M&M Systems",
    117: "Custom Software Engineering",
    118: "Nittan Company, Limited",
    119: "Elutions Inc. (Wizcon Systems SAS)",
    120: "Pacom Systems Pty",
    121: "Unico",
    122: "Ebtron",
    123: "Scada Engine",
    124: "Lenze Americas",
    125: "Eagle Technology",
    126: "Data Aire",
    127: "ABB",
    128: "Transbit Sp. z o. o",
    129: "Carrier Japan",
    130: "Shenzhen Junzhi Hi-Tech",
    131: "Tokai Soft",
    132: "Blue Ridge Technologies",
    133: "Veris Industries",
    134: "Centaurus Prime",
    135: "Sand Network Systems",
    136: "Regulvar",
    137: "AFDtek Division of Fastek International",
    138: "PowerCold Comfort Air Solutions",
    139: "I Controls",
    140: "Viconics Electronics",
    141: "Yaskawa America",
    142: "DEOS control systems",
    143: "Digitale Mess- und Steuersysteme",
    144: "Fujitsu General Limited",
    145: "Project Engineering S.r.l",
    146: "Sanyo Electric",
    147: "Integrated Information Systems",
    148: "Temco Controls",
    149: "Airtek International",
    150: "Advantech",
    151: "Titan Products",
    152: "Regel Partners",
    153: "National Environmental Product",
    154: "Unitec",
    155: "Kanden Engineering Company",
    156: "Messner Gebäudetechnik",
    157: "Integrated.CH",
    158: "Price Industries",
    159: "SE-Elektronic",
    160: "Rockwell Automation",
    161: "Enflex",
    162: "ASI Controls",
    163: "SysMik GmbH Dresden",
    164: "HSC Regelungstechnik",
    165: "Smart Temp Australia Pty",
    166: "Cooper Controls",
    167: "Duksan Mecasys",
    168: "Fuji IT",
    169: "Vacon Plc",
    170: "Leader Controls",
    171: "ABB (Formerly Cylon Controls)",
    172: "Compas",
    173: "Mitsubishi Electric Building Techno-Service",
    174: "Building Control Integrators",
    175: "ITG Worldwide (M) Sdn Bhd",
    176: "Lutron Electronics Co",
    177: "Cooper-Atkins",
    178: "LOYTEC Electronics",
    179: "ProLon",
    180: "Mega Controls Limited",
    181: "Micro Control Systems",
    182: "Kiyon",
    183: "Dust Networks",
    184: "Advanced Building Automation Systems",
    185: "Hermos",
    186: "CEZIM",
    187: "Softing",
    188: "Lynxspring",
    189: "Schneider Toshiba Inverter Europe",
    190: "Danfoss Drives A/S",
    191: "Eaton",
    192: "Matyca S.A",
    193: "Botech",
    194: "Noveo",
    195: "AMEV",
    196: "Yokogawa Electric",
    197: "Bosch Building Automation",
    198: "Exact Logic",
    199: "Innotech Control Systems Australia",
    200: "Kandenko",
    201: "DTF, Daten-Technik Fries",
    202: "Klimasoft",
    203: "Toshiba Schneider Inverter",
    204: "Control Applications",
    205: "CIMON",
    206: "Onicon Incorporated",
    207: "Automation Displays",
    208: "Control Solutions",
    209: "Remsdaq Limited",
    210: "NTT Facilities",
    211: "VIPA",
    212: "TSC21 Association of Japan",
    213: "Strato Automation",
    214: "HRW Limited",
    215: "Lighting Control & Design",
    216: "Mercy Electronic and Electrical Industries",
    217: "Samsung SDS",
    218: "Impact Facility Solutions",
    219: "Aircuity",
    220: "Control Techniques",
    221: "OpenGeneral Pty",
    222: "WAGO Kontakttechnik GmbH & Co. KG",
    223: "Franklin Electric",
    224: "Chloride Power Protection Company",
    225: "Computrols",
    226: "Phoenix Contact GmbH & Co. KG",
    227: "Grundfos Management A/S",
    228: "Ridder Drive Systems",
    229: "Soft Device SDN BHD",
    230: "Integrated Control Technology Limited",
    231: "AIRxpert Systems",
    232: "Microtrol Limited",
    233: "Red Lion Controls",
    234: "Digital Electronics",
    235: "Ennovatis",
    236: "Serotonin Software Technologies",
    237: "LS Industrial Systems",
    238: "Square D Company",
    239: "S Squared Innovations",
    240: "Aricent",
    241: "EtherMetrics",
    242: "Industrial Control Communications",
    243: "Paragon Controls",
    244: "A. O. Smith",
    245: "Contemporary Control Systems",
    246: "HMS Industrial Networks SLU",
    247: "Ingenieurgesellschaft N. Hartleb mbH",
    248: "Heat-Timer",
    249: "Ingrasys Technology",
    250: "Costerm Building Automation",
    251: "WILO SE",
    252: "Embedia Technologies",
    253: "Technilog",
    254: "HR Controls Ltd. & Co. KG",
    255: "Lennox International",
    256: "RK-Tec Rauchklappen-Steuerungssysteme",
    257: "Thermomax",
    258: "ELCON Electronic Control",
    259: "Larmia Control",
    260: "BACnet Stack at SourceForge",
    261: "G4S Security Services A/S",
    262: "Exor International",
    263: "Cristal Controles",
    264: "Regin",
    265: "Dimension Software",
    266: "SynapSense",
    267: "Beijing Nantree Electronic",
    268: "Camus Hydronics",
    269: "Kawasaki Heavy Industries",
    270: "Critical Environment Technologies",
    271: "ILSHIN IBS",
    272: "ELESTA Energy Control",
    273: "KROPMAN Installatietechniek",
    274: "Baldor Electric Company",
    275: "INGA mbH",
    276: "GE Consumer & Industrial",
    277: "Functional Devices",
    278: "StudioSC",
    279: "MG",
    280: "Yokota",
    281: "Hitranse Technology",
    282: "Vigilent",
    283: "Kele",
    284: "BELIMO Automation",
    285: "Gentec",
    286: "Embedded Science Labs",
    287: "Parker Hannifin",
    288: "MaCaPS International Limited",
    289: "Link4",
    290: "Romutec Steuer-u. Regelsysteme",
    291: "Pribusin",
    292: "Advantage Controls",
    293: "Critical Room Control",
    294: "LEGRAND",
    295: "Tongdy Control Technology",
    296: "ISSARO Integrierte Systemtechnik",
    297: "Pro-Dev Industries",
    298: "DRI-STEEM",
    299: "Creative Electronic",
    300: "Swegon",
    301: "FIRVENA s.r.o",
    302: "Hitachi Appliances",
    303: "Real Time Automation",
    304: "ITEC Hankyu-Hanshin Co",
    305: "Cyrus E&M Engineering",
    306: "Badger Meter",
    307: "Cirrascale",
    308: "Elesta GmbH Building Automation",
    309: "Securiton",
    310: "OSlsoft",
    311: "Hanazeder Electronic",
    312: "Honeywell Security Deutschland, Novar",
    313: "Siemens Industry",
    314: "ETM Professional Control",
    315: "Meitav-tec",
    316: "Janitza Electronics",
    317: "MKS Nordhausen",
    318: "De Gier Drive Systems B.V",
    319: "Cypress Envirosystems",
    320: "SMARTron s.r.o",
    321: "Verari Systems",
    322: "K-W Electronic Service",
    323: "ALFA-SMART Energy Management",
    324: "Telkonet",
    325: "Securiton",
    326: "Cemtrex",
    327: "Performance Technologies",
    328: "Xtralis (Aust) Pty",
    329: "TROX SE",
    330: "Beijing Hysine Technology",
    331: "RCK Controls",
    332: "Distech Controls SAS",
    333: "Novar / Honeywell",
    334: "S4 Integration Solutions",
    335: "Schneider Electric",
    336: "LHA Systems",
    337: "GHM engineering Group",
    338: "Cllimalux S.A",
    339: "VAISALA Oyj",
    340: "COMPLEX (Beijing) Technology",
    341: "SCADAmetrics",
    342: "POWERPEG NSI Limited",
    343: "BACnet Interoperability Testing Services",
    344: "Teco a.s",
    345: "Plexus Technology",
    346: "Energy Focus",
    347: "Powersmiths International",
    348: "Nichibei",
    349: "HKC Technology",
    350: "Ovation Networks",
    351: "Setra Systems",
    352: "AVG Automation",
    353: "ZXC",
    354: "Byte Sphere",
    355: "Generiton",
    356: "Holter Regelarmaturen GmbH & Co. KG",
    357: "Bedford Instruments",
    358: "Standair",
    359: "WEG Automation",
    360: "Prolon Control Systems ApS",
    361: "Inneasoft",
    362: "ConneXSoft",
    363: "CEAG Notlichtsysteme",
    364: "Distech Controls",
    365: "Industrial Technology Research Institute",
    366: "Mitsubishi Electric Iconics Digital Solutions",
    367: "IQ Controls s.c",
    368: "OJ Electronics A/S",
    369: "Rolbit",
    370: "Synapsys Solutions",
    371: "ACME Engineering Prod",
    372: "Zener Electric Pty",
    373: "Selectronix",
    374: "Gorbet & Banerjee",
    375: "IME",
    376: "Stephen H. Dawson Computer Service",
    377: "Accutrol",
    378: "Schneider Elektronik",
    379: "Alpha-Inno Tec",
    380: "ADMMicro",
    381: "Greystone Energy Systems",
    382: "CAP Technologie",
    383: "KeRo Systems",
    384: "Domat Control System s.r.o",
    385: "Efektronics Pty",
    386: "Hekatron Vertriebs",
    387: "Securiton",
    388: "Carlo Gavazzi Controls SpA",
    389: "Chipkin Automation Systems",
    390: "Savant Systems",
    391: "Simmtronic Lighting Controls",
    392: "Abelko Innovation",
    393: "Seresco Technologies",
    394: "IT Watchdogs",
    395: "Automation Assist Japan",
    396: "Thermokon Sensortechnik",
    397: "EGauge Systems",
    398: "Quantum Automation (ASIA) PTE",
    399: "Toshiba Lighting & Technology",
    400: "SPIN Engenharia de Automação Ltda",
    401: "Logistics Systems & Software Services India PVT",
    402: "Delta Controls Integration Products",
    403: "Focus Media",
    404: "LUMEnergi",
    405: "Kara Systems",
    406: "RF Code",
    407: "Fatek Automation",
    408: "JANDA Software Company",
    409: "Open System Solutions Limited",
    410: "Intelec Systems PTY",
    411: "Ecolodgix",
    412: "Douglas Lighting Controls",
    413: "iSAtech",
    414: "AREAL",
    415: "Beckhoff Automation",
    416: "IPAS",
    417: "KE2 Therm Solutions",
    418: "Base2Products",
    419: "DTL Controls",
    420: "INNCOM International",
    421: "METZ CONNECT",
    422: "Greentrol Automation",
    423: "BELIMO Automation",
    424: "Samsung Heavy Industries",
    425: "Triacta Power Technologies",
    426: "Globestar Systems",
    427: "MLB Advanced Media, LP",
    428: "SWG Stuckmann Wirtschaftliche Gebäudesysteme",
    429: "SensorSwitch",
    430: "Multitek Power Limited",
    431: "Integra Metering",
    432: "LG Electronics",
    433: "Electronic Theatre Controls",
    434: "Mitsubishi Electric Corporation Nagoya Works",
    435: "Delta Electronics",
    436: "Elma Kurtalj",
    437: "Tyco Fire & Security",
    438: "Nedap Security Management",
    439: "ESC Automation",
    440: "DSP4YOU",
    441: "GE Sensing and Inspection Technologies",
    442: "Embedded Systems SIA",
    443: "BEFEGA",
    444: "Baseline",
    445: "Key2Act",
    446: "OEMCtrl",
    447: "Clarkson Controls Limited",
    448: "Rogerwell Control System Limited",
    449: "SCL Elements",
    450: "Hitachi",
    451: "Newron System",
    452: "BEVECO Gebouwautomatisering",
    453: "Streamside Solutions",
    454: "Yellowstone Soft",
    455: "Oztech Intelligent Systems Pty",
    456: "Novelan",
    457: "Flexim Americas",
    458: "ICP DAS",
    459: "CARMA Industries",
    460: "Log-One",
    461: "TECO Electric & Machinery",
    462: "ConnectEx",
    463: "Turbo DDC Südwest",
    464: "Quatrosense Environmental",
    465: "Fifth Light Technology",
    466: "Scientific Solutions",
    467: "Controller Area Network Solutions (M) Sdn Bhd",
    468: "RESOL - Elektronische Regelungen",
    469: "RPBUS",
    470: "BRS Sistemas Eletronicos",
    471: "WindowMaster A/S",
    472: "Sunlux Technologies",
    473: "Measurlogic",
    474: "Frimat",
    475: "Spirax Sarco",
    476: "Luxtron",
    477: "Raypak",
    478: "Air Monitor",
    479: "Regler Och Webbteknik Sverige (ROWS)",
    480: "Intelligent Lighting Controls",
    481: "Sanyo Electric Industry",
    482: "E-Mon Energy Monitoring Products",
    483: "Digital Control Systems",
    484: "ATI Airtest Technologies",
    485: "SCS",
    486: "HMS Industrial Networks",
    487: "Shenzhen Universal Intellisys",
    488: "EK Intellisys Sdn Bhd",
    489: "SysCom",
    490: "Firecom",
    491: "ESA Elektroschaltanlagen Grimma",
    492: "Kumahira",
    493: "Hotraco",
    494: "SABO Elektronik",
    495: "Equip'Trans",
    496: "Temperature Control Specialities Co., Inc (TCS)",
    497: "FlowCon International A/S",
    498: "ThyssenKrupp Elevator Americas",
    499: "Abatement Technologies",
    500: "Continental Control Systems",
    501: "WISAG Automatisierungstechnik GmbH & Co KG",
    502: "EasyIO",
    503: "EAP-Electric",
    504: "Hardmeier",
    505: "Mircom Group of Companies",
    506: "Quest Controls",
    507: "Mestek",
    508: "Pulse Energy",
    509: "Tachikawa",
    510: "University of Nebraska-Lincoln",
    511: "Redwood Systems",
    512: "PASStec Industrie-Elektronik",
    513: "NgEK",
    514: "t-mac Technologies",
    515: "Jireh Energy Tech",
    516: "Enlighted",
    517: "El-Piast Sp. Z o.o",
    518: "NetxAutomation Software",
    519: "Invertek Drives",
    520: "Deutschmann Automation GmbH & Co. KG",
    521: "EMU Electronic",
    522: "Phaedrus Limited",
    523: "Sigmatek GmbH & Co KG",
    524: "Marlin Controls",
    525: "Circutor",
    526: "UTC Fire & Security",
    527: "DENT Instruments",
    528: "FHP Manufacturing Company - Bosch Group",
    529: "GE Intelligent Platforms",
    530: "Inner Range Pty",
    531: "GLAS Energy Technology",
    532: "MSR-Electronic-",
    533: "Energy Control Systems",
    534: "EMT Controls",
    535: "Daintree",
    536: "EURO ICC d.o.o",
    537: "TE Connectivity Energy",
    538: "GEZE",
    539: "NEC",
    540: "Ho Cheung International Company Limited",
    541: "Sharp Manufacturing Systems",
    542: "DOT CONTROLS a.s",
    543: "BeaconMedæs",
    544: "Midea Commercial Aircon",
    545: "AAON",
    546: "Kamstrup A/S",
    547: "CA Computer Automation",
    548: "Laars Heating Systems Company",
    549: "Hitachi Systems",
    550: "Fushan AKE Electronic Engineering",
    551: "Toshiba International",
    552: "Starman Systems",
    553: "Samsung Techwin",
    554: "ISAS-Integrated Switchgear and Systems",
    556: "Obvius",
    557: "Marek Guzik",
    558: "Vortek Instruments",
    559: "Universal Lighting Technologies",
    560: "Myers Power Products",
    561: "Vector Controls",
    562: "Crestron Electronics",
    563: "A&E Controls Limited",
    564: "Projektomontaza A.D",
    565: "Freeaire Refrigeration",
    566: "Aqua Cooler Pty Limited",
    567: "Basic Controls",
    568: "GE Measurement and Control Solutions",
    569: "EQUAL Networks",
    570: "Millennial Net",
    571: "APLI",
    572: "Electro Industries/GaugeTech",
    573: "SangMyung University",
    574: "Coppertree Analytics",
    575: "CoreNetiX",
    576: "Acutherm",
    577: "Dr. Riedel Automatisierungstechnik",
    578: "Shina System",
    579: "Iqapertus",
    580: "PSE Technology",
    581: "BA Systems",
    582: "BTICINO",
    583: "Monico",
    584: "iCue",
    585: "tekmar Control Systems",
    586: "Control Technology",
    587: "GFAE",
    588: "BeKa Software",
    589: "Isoil Industria SpA",
    590: "Home Systems Consulting SpA",
    591: "Socomec",
    592: "Everex Communications",
    593: "CET Electric Technology",
}

# ---------------------------------------------------------------------------
# HTTP / banner fingerprints: (regex, vendor label)
# Applied against banner + title + server + product text.
# ---------------------------------------------------------------------------
HTTP_FINGERPRINTS = [
    (r"trane|tracer",                                   "Trane"),
    (r"siemens|desigo",                                 "Siemens"),
    (r"honeywell|webs|spyder|tridium|niagara",          "Honeywell / Tridium"),
    (r"johnson.?controls|metasys|fec|nae",              "Johnson Controls"),
    (r"schneider|ecostruxure|smartx|andover",           "Schneider Electric"),
    (r"carrier|i-?vu|alerton",                          "Carrier / ALC"),
    (r"automated.?logic|webctrl",                       "Automated Logic"),
    (r"daikin",                                         "Daikin"),
    (r"distech",                                        "Distech Controls"),
    (r"delta.?controls",                                "Delta Controls"),
    (r"reliable.?controls",                             "Reliable Controls"),
    (r"kmc|flexstat|bac-?net",                          "KMC Controls"),
    (r"carel|pco",                                      "Carel"),
    (r"belimo",                                         "Belimo"),
    (r"easyio",                                         "EasyIO"),
    (r"loytec",                                         "Loytec"),
    (r"beckhoff",                                       "Beckhoff"),
    (r"wago",                                           "WAGO"),
    (r"emerson|copeland|vertiv",                        "Emerson"),
    (r"danfoss",                                        "Danfoss"),
    (r"mitsubishi.?electric|melco|city.?multi",         "Mitsubishi Electric"),
    (r"lg.?electronics|lgap|multi.?v",                  "LG Electronics"),
    (r"samsung|dvm",                                    "Samsung HVAC"),
    (r"ubiquiti|unifi",                                 "Ubiquiti"),
]

# ---------------------------------------------------------------------------
# Default credentials database. STRICTLY for the legitimate owner/operator
# of their own BAS. Factory defaults that every integrator already knows.
# ---------------------------------------------------------------------------
DEFAULT_CREDS = {
    'Trane Tracer SC':                  'admin / Tracer1$  |  Trane / Tr@n3',
    'Trane Tracer SC+':                 'admin / Tracer1$',
    'Trane Tracer UC':                  '(no default auth on web UI)',
    'Siemens Desigo PXC':               'ADMIN / SBTAdmin!1',
    'Siemens Desigo CC':                'Application login (site-configured)',
    'Siemens Desigo Insight':           'admin / (site-configured)',
    'Johnson Controls Metasys':         'MetasysAgent / MetasysAgent  |  admin / JCI-admin',
    'Johnson Controls FEC':             'admin / admin',
    'Honeywell Tridium Niagara':        'admin / (set at install)',
    'Schneider EcoStruxure':            'USER1 / USER1  |  admin / admin',
    'Automated Logic WebCTRL':          'admin / admin',
    'Contemporary Controls BASRT-B':    'admin / admin',
    'Carrier i-Vu':                     'admin / admin',
    'KMC Controls':                     'admin / admin',
    'Distech Controls':                 'admin / admin',
    'Reliable Controls':                'admin / admin',
    'Delta Controls':                   'admin / admin',
    'Carel pCO':                        'admin / admin  |  user / user',
    'Belimo':                           'admin / belimo',
    'EasyIO':                           'admin / admin',
    'Daikin':                           'admin / admin',
    'Nucleus FTP (Siemens)':            'admin / admin  |  ADMIN / SBTAdmin!1',
}


# ---------------------------------------------------------------------------
# Property identifiers used by the scanner
# ---------------------------------------------------------------------------
PROP_IDS = {
    'objectName':                   77,
    'objectList':                   76,
    'presentValue':                 85,
    'description':                  28,
    'units':                        117,
    'vendorName':                   121,
    'modelName':                    70,
    'firmwareRevision':             44,
    'applicationSoftwareVersion':   12,
    'objectIdentifier':             75,
    'protocolVersion':              98,
    'protocolRevision':             139,
    'systemStatus':                 112,
    'databaseRevision':             155,
    # hyphenated aliases for convenience
    'object-name':                  77,
    'object-list':                  76,
    'present-value':                85,
    'vendor-name':                  121,
    'model-name':                   70,
    'firmware-revision':            44,
    'application-software-version': 12,
    'protocol-version':             98,
    'protocol-revision':            139,
    'system-status':                112,
}

# Default property set read during device discovery (deep scan)
DEFAULT_DEVICE_PROPERTIES = [
    'object-name',
    'vendor-name',
    'model-name',
    'firmware-revision',
    'application-software-version',
    'description',
    'protocol-version',
    'protocol-revision',
]

# Default property set read per point (deep scan)
DEFAULT_POINT_PROPERTIES = [
    'presentValue',
    'objectName',
    'units',
    'description',
]

# v2.1.1: Per-object-type property lists. Asking units of a Binary Input or
# presentValue of a Calendar wastes a round-trip and returns "unknown property",
# filling the scan log with garbage. This map tells the scanner which properties
# actually exist for which object types. Any object type not in this map falls
# back to DEFAULT_POINT_PROPERTIES.
# Reference: ASHRAE 135 property-list-per-object-type tables.
POINT_PROPERTIES_BY_TYPE = {
    # Analog points: have present value, units, name, description
    'Analog Input':         ['objectName', 'presentValue', 'units', 'description'],
    'Analog Output':        ['objectName', 'presentValue', 'units', 'description'],
    'Analog Value':         ['objectName', 'presentValue', 'units', 'description'],
    'Loop':                 ['objectName', 'presentValue', 'units', 'description'],
    'Accumulator':          ['objectName', 'presentValue', 'units', 'description'],
    'Pulse Converter':      ['objectName', 'presentValue', 'units', 'description'],
    'Averaging':            ['objectName', 'presentValue', 'units', 'description'],
    'Integer Value':        ['objectName', 'presentValue', 'units', 'description'],
    'Positive Integer Value': ['objectName', 'presentValue', 'units', 'description'],
    'Large Analog Value':   ['objectName', 'presentValue', 'units', 'description'],
    'Lighting Output':      ['objectName', 'presentValue', 'units', 'description'],

    # Binary points: have present value, name, description — but NO units
    'Binary Input':         ['objectName', 'presentValue', 'description'],
    'Binary Output':        ['objectName', 'presentValue', 'description'],
    'Binary Value':         ['objectName', 'presentValue', 'description'],
    'Binary Lighting Output': ['objectName', 'presentValue', 'description'],

    # Multi-state: have present value, name, description — NO units
    'Multi-State Input':    ['objectName', 'presentValue', 'description'],
    'Multi-State Output':   ['objectName', 'presentValue', 'description'],
    'Multi-State Value':    ['objectName', 'presentValue', 'description'],

    # Character string / date / time values
    'CharacterString Value': ['objectName', 'presentValue', 'description'],
    'DateTime Value':       ['objectName', 'presentValue', 'description'],
    'Date Value':           ['objectName', 'presentValue', 'description'],
    'Time Value':           ['objectName', 'presentValue', 'description'],
    'BitString Value':      ['objectName', 'presentValue', 'description'],
    'OctetString Value':    ['objectName', 'presentValue', 'description'],

    # Access control / life safety: have present value but rarely units
    'Access Door':          ['objectName', 'presentValue', 'description'],
    'Life Safety Point':    ['objectName', 'presentValue', 'description'],
    'Life Safety Zone':     ['objectName', 'presentValue', 'description'],
    'Command':              ['objectName', 'description'],

    # Config/navigational objects — name + description only, no present value
    'Group':                ['objectName', 'description'],
    'Global Group':         ['objectName', 'description'],
    'Network Port':         ['objectName', 'description'],
    'Timer':                ['objectName', 'presentValue', 'description'],
    'Elevator Group':       ['objectName', 'description'],
    'Escalator':            ['objectName', 'description'],
    'Event Enrollment':     ['objectName', 'description'],
    'Load Control':         ['objectName', 'presentValue', 'description'],
    'Channel':              ['objectName', 'description'],
}
